/** Le Cloître des pratiques — dépôt d’un travail ou d’une proposition dans toute discipline, avec retour local explicite. */
import { useState } from "react";
import { ArrowLeft, Send } from "lucide-react";
import { InkButton, SiteShell } from "@/components/PoiesisUI";

export default function SubmitEcho() {
  const [sent, setSent] = useState(false);
  return <SiteShell><section className="echo-page"><a className="back-link" href="/create"><ArrowLeft size={15} />Back to the studios</a><div className="submit-leaf">{!sent ? <><div className="submit-leaf__intro"><p className="section-tag"><span />Share a work</p><h1>Put a practice<br />into the room.</h1><p>Share a sculpture proposal, a photograph, a sound, a film note, a movement score, a text, a design, a question or an event idea.</p><Send size={30} /></div><form onSubmit={(e) => { e.preventDefault(); setSent(true); }}><label>Title<input required placeholder="Give the work or idea a title" /></label><label>Practice<select defaultValue="visual"><option value="visual">Visual art / sculpture</option><option value="photo-film">Photography / film</option><option value="music-sound">Music / sound</option><option value="stage">Dance / theatre / performance</option><option value="writing">Writing / publishing</option><option value="culture-thought">Culture / philosophy / debate</option><option value="design">Design / digital / craft</option></select></label><label>Description, link or proposal<textarea required rows={7} placeholder="Describe the work, add a link, or explain the session you would like to propose." /></label><label className="check-label"><input type="checkbox" required /> I am ready for other members to meet this contribution with care.</label><InkButton type="submit">Share with the house</InkButton></form></> : <div className="success-panel submit-success"><span>✦</span><h2>Your contribution is ready for the house.</h2><p>This is a local confirmation only. Connect storage or a form destination to collect real contributions.</p><InkButton href="/create" tone="ink">Return to the studios</InkButton></div>}</div></section></SiteShell>;
}
